apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezlearn
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: ezlearn
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ezlearn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ezlearn
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: ezlearn
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          readinessProbe:
            httpGet: { path: "/", port: {{ .Values.service.targetPort }} }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: {{ .Values.service.targetPort }} }
            initialDelaySeconds: 60
            periodSeconds: 20
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: webapps
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: webapps
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
