---
- name: Create sonar user
  ansible.builtin.user:
    name: sonar
    shell: /bin/false
    create_home: no

- name: Download SonarQube
  ansible.builtin.get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
    dest: /tmp/sonarqube.zip

- name: Extract SonarQube
  ansible.builtin.unarchive:
    src: /tmp/sonarqube.zip
    dest: /opt/
    remote_src: yes

- name: Set ownership for SonarQube
  ansible.builtin.file:
    path: /opt/sonarqube-9.9.0.65466
    owner: sonar
    group: sonar
    recurse: yes

- name: Create SonarQube systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/sonarqube.service
    content: |
      [Unit]
      Description=SonarQube service
      After=network.target

      [Service]
      Type=simple
      User=sonar
      Group=sonar
      ExecStart=/opt/sonarqube-9.9.0.65466/bin/linux-x86-64/sonar.sh start
      ExecStop=/opt/sonarqube-9.9.0.65466/bin/linux-x86-64/sonar.sh stop
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and enable SonarQube
  ansible.builtin.systemd:
    daemon_reload: yes
    name: sonarqube
    state: started
    enabled: yes
