plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Environment: prod
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""
    lowercase: true

hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
  # ansible_user: ubuntu