plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Env: prod
keyed_groups:
  - key: tags.Name
    prefix: ""
    lowercase: true
    separator: "_"
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address