---
- name: Download Dynatrace OneAgent installer
  get_url:
    url: "{{ dynatrace_env_url }}/api/v1/deployment/installer/agent/unix/default/latest?arch={{ dynatrace_arch }}"
    headers:
      Authorization: "Api-Token {{ dynatrace_api_token }}"
    dest: "{{ dynatrace_installer }}"
    mode: '0755'
    force: yes

- name: Run the Dynatrace OneAgent installer
  shell: >
    /bin/sh {{ dynatrace_installer }}
    --set-monitoring-mode={{ dynatrace_mode }}
    --set-app-log-content-access=true
  args:
    creates: /opt/dynatrace/oneagent

- name: Set custom Dynatrace hostname after install
  command: >
    /opt/dynatrace/oneagent/agent/tools/oneagentctl --set-host-name={{ inventory_hostname }}

- name: Restart Dynatrace OneAgent service
  systemd:
    name: oneagent
    state: restarted
