apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: nexus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexus
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      containers:
        - name: nexus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet: { path: "/", port: {{ .Values.service.targetPort }} }
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: {{ .Values.service.targetPort }} }
            initialDelaySeconds: 120
            periodSeconds: 20
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
