apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: {{ .Values.namespace }}
  labels: { app: sonarqube }
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: sonarqube }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
