namespace: ezlearn-dev-ns

image:
  repository: mitechllc/ezlearn
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecret: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}

ingress:
  enabled: true
  className: traefik           # or nginx
  host: ezlearn-dev.mitechnology.org
  path: /
  annotations: {}
  tls:
    enabled: false
    secretName: ""

persistence:
  enabled: true
  existingClaim: "tomcat-webapps-pvc"
  mountPath: "/usr/local/tomcat/webapps"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
