---
- name: Install Java 17
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Create tomcat group
  ansible.builtin.group:
    name: tomcat

- name: Create tomcat user
  ansible.builtin.user:
    name: tomcat
    group: tomcat
    shell: /bin/false
    create_home: false

- name: Download Tomcat 9.0.82
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz
    dest: /tmp/tomcat.tar.gz

- name: Create Tomcat install directory
  ansible.builtin.file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract Tomcat
  ansible.builtin.unarchive:
    src: /tmp/tomcat.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: tomcat
    group: tomcat

- name: Set permissions on key Tomcat folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes
  loop:
    - /opt/tomcat/bin
    - /opt/tomcat/webapps
    - /opt/tomcat/conf
    - /opt/tomcat/logs

- name: Configure tomcat-users.xml
  ansible.builtin.copy:
    dest: /opt/tomcat/conf/tomcat-users.xml
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <tomcat-users>
        <role rolename="manager-gui"/>
        <role rolename="admin-gui"/>
        <user username="admin" password="admin123" roles="manager-gui,admin-gui"/>
      </tomcat-users>
    owner: tomcat
    group: tomcat
    mode: '0640'

- name: Create Tomcat systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/tomcat.service
    content: |
      [Unit]
      Description=Apache Tomcat Web Application Container
      After=network.target

      [Service]
      Type=forking
      Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
      Environment=CATALINA_HOME=/opt/tomcat
      Environment=CATALINA_BASE=/opt/tomcat
      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh
      User=tomcat
      Group=tomcat
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Restart Tomcat

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable Tomcat service
  ansible.builtin.systemd:
    name: tomcat
    enabled: yes

- name: Restart Tomcat
  ansible.builtin.systemd:
    name: tomcat
    state: restarted    
