---
- name: Ensure base system packages are installed
  ansible.builtin.apt:
    name:
      - openjdk-17-jdk
      - unzip
      - curl
      - software-properties-common
      - fontconfig
    state: present
    update_cache: yes
