---
- name: Jenkins Master and Slave Setup
  hosts: jenkins_master:jenkins_slave
  become: yes
  roles:
    - common
    - maven

- name: Install Jenkins Master
  hosts: jenkins_master
  become: yes
  roles:
    - jenkins_master

- name: Configure Jenkins Slave
  hosts: jenkins_slave
  become: yes
  roles:
    - jenkins_slave
