---
- name: Install Maven only on Jenkins Slave
  hosts: jenkins_slave
  become: yes
  roles:
    - maven

- name: Setup SonarQube
  hosts: sonarqube
  become: yes
  roles:
    - sonarqube

- name: Setup Nexus
  hosts: nexus
  become: yes
  roles:
    - nexus

- name: Setup Tomcat
  hosts: tomcat
  become: yes
  roles:
    - tomcat
